"""The pinned integrity of the Node.js core the bridge loads.

GENERATED by ``scripts/core-integrity.py write``; do not edit.

``tree`` is the "rsv-tree-v1" digest of the package's directory as npm installs it: SHA-256 over one line per regular
file, ``<sha256 of the content> <size> <relative path>`` sorted by the UTF-8 bytes of the path. ``tarball`` is the npm
``integrity`` value of the published tarball (``package-lock.json``), kept so that a reviewer can see the pin and the
lock agree. ``scripts/core-integrity.py check`` recomputes every ``tree`` from the published tarballs in CI.
"""

from __future__ import annotations

ALGORITHM = "rsv-tree-v1"

CORE_PACKAGES = {
    "@redact-secret/core": {
        "version": "0.1.0-beta.12",
        "tarball": "sha512-fDVwt2U7VFSKb/0ixSuU5e+TOGVaUnyR1sIYwgS4S6gMndFnaq0M7ikaqac8wnTMYfYO/LS12JayXXeKbhE4aw==",
        "tree": "7351ffda313fc4527e6041261870cbce7ff9919793890f5c3fb8947db19a59ac",
    },
    "@redact-secret/wasm": {
        "version": "0.1.0-beta.12",
        "tarball": "sha512-i9XV+P0j92z+00jujDe9MQdnniYGirSf3VJkqWe9iUwcn8T4e0++euDqxthIWXRQykIYPoHduM7AVyeUwo6iKg==",
        "tree": "08a55e20ba9932a6781af26f47f7b015e7d05538f114283129980af73ae2e27c",
    },
    "@redact-secret/node-darwin-arm64": {
        "version": "0.1.0-beta.12",
        "tarball": "sha512-xAA09sFA0bX1+4Ab7fT8Irgf3eLL0+SWB0hvVZ61xuR5WOGhKxpSFOgU1Gteyp/EmvX2RksqYEySijXYiRd+PA==",
        "tree": "4cfe68b33ba56373fa427ae49a1676450331b3318c7a395dbd304c399b0d0b26",
    },
    "@redact-secret/node-darwin-x64": {
        "version": "0.1.0-beta.12",
        "tarball": "sha512-0R4AsXsXg5HDrYWCPC1dwIeNj+21oF2FN0K3QawStTieEVPKt1gu/dYpgl9zmYAfddgzGUeEaPyOS3KenIrF7A==",
        "tree": "35d21428016a134e236adeafd3cdfd317d89541f78f7f0d4c43dcd4d247f24ef",
    },
    "@redact-secret/node-linux-arm64-gnu": {
        "version": "0.1.0-beta.12",
        "tarball": "sha512-ONmz+lCrQhZo63+o0ny7Cpm+e5RoQnOuDa15djEor7jLFMytHBP7Zwf77kY8m6S8r9/MuglYtrXY7uvcqAl6Xg==",
        "tree": "4c105240e666fde74885a2d1ed68af2e8685eb4c2e95f76a6f1d7c61418a118d",
    },
    "@redact-secret/node-linux-arm64-musl": {
        "version": "0.1.0-beta.12",
        "tarball": "sha512-AesR9/xWVYDFKnyhF+Z76oN06z6u+CXxaGCwh6u0ViIgMTlxdEdy7H7/IHhXzybu/+QMjO5+KK9gAXAGdV6yUQ==",
        "tree": "a84dd74e9572aa6c4a25daa440d811da6830d4458cd0ed6a1b92f97becb98dd3",
    },
    "@redact-secret/node-linux-x64-gnu": {
        "version": "0.1.0-beta.12",
        "tarball": "sha512-uf66fX2ngvXO9itiettZjrMvUKHbTa9zGRX4ZB9JfGsY+m1EWm2sWqtwtff07P/ajaF3Ioe0Vt6ktJz/I69b3w==",
        "tree": "5163f55588966397d9855fdfe762aa30f77524927feea464f13589228121c68b",
    },
    "@redact-secret/node-linux-x64-musl": {
        "version": "0.1.0-beta.12",
        "tarball": "sha512-TbMkRyyHYpVN5kL8IkiF0mpZe+KBo7TG52WwMOHK5TwFBKccNRuaFjGu8WkyMZt9HAoLsEato98OLuXCZrLDbA==",
        "tree": "073f9a3585d34596de93b7c6b73b50eff7fab0ca3d68e099514a74d4083b5829",
    },
    "@redact-secret/node-win32-arm64-msvc": {
        "version": "0.1.0-beta.12",
        "tarball": "sha512-oH2E5owPI9vyMGdnqbKLywAiD/lC5ZKdociHXqbKMRqplTKcULd7op9p8na3ZSLLXbMO9/yntahFM8A51gfu9A==",
        "tree": "831e985cf537262b32ada3f4dd6cc6ddcd7cd9ccd347758e83b74303faa5a07d",
    },
    "@redact-secret/node-win32-x64-msvc": {
        "version": "0.1.0-beta.12",
        "tarball": "sha512-fqa29XtVahqQbakik+/Y57GKe91witJHiPPk8+3m5usytrz+AP6v+AWny80X5Pssj5HzBzFuMHXiSKAWevKlTA==",
        "tree": "bb9616b433f82e557f4f7351e91cbd9498280245fd739f9e3d8885af7c9292ff",
    },
}
