"""The pinned integrity of the Node.js core the bridge loads.

GENERATED by ``scripts/core-integrity.py write``; do not edit.

``tree`` is the "rsv-tree-v1" digest of the package's directory as npm installs it: SHA-256 over one line per regular
file, ``<sha256 of the content> <size> <relative path>`` sorted by the UTF-8 bytes of the path. ``tarball`` is the npm
``integrity`` value of the published tarball (``package-lock.json``), kept so that a reviewer can see the pin and the
lock agree. ``scripts/core-integrity.py check`` recomputes every ``tree`` from the published tarballs in CI.
"""

from __future__ import annotations

ALGORITHM = "rsv-tree-v1"

CORE_PACKAGES = {
    "@redact-secret/core": {
        "version": "0.1.0-beta.13",
        "tarball": "sha512-qZkqRN7CIJ+pc0IteRCXSucr1l9KtTc/nJaM5wPL0NvCiZ4AGWLCyrLy8KD95a2MBgxo8vuUJ/UaKhrny7gMJQ==",
        "tree": "d46b1298daddd57b436387060e2bf2ddcc3e539fb0d04cf597ff67846e28fbfa",
    },
    "@redact-secret/wasm": {
        "version": "0.1.0-beta.13",
        "tarball": "sha512-mTf82nZ6/2ObrqX1lOvqpSlpp6Y1R/jGJU/LTUGGSPzY5lgrZmH6g6V5Rjl8IsjKFNm/nQsVWyQq00WG5Rmo0g==",
        "tree": "b802191317ad33b33b0db0cb669ec8ffda0c66e1b92e3e73d431b7b9e61d56ad",
    },
    "@redact-secret/node-darwin-arm64": {
        "version": "0.1.0-beta.13",
        "tarball": "sha512-W1R5oKVzX6liurnDrRMnh8DYzFEqn0vjPcbSQZYkIvZaUwFm9JEEvPF1TV4uTx8Xu+nw9uaW6B5GKCLls58dsg==",
        "tree": "8adb6723bfd5145bbd8a6b2e1c45c1834cd819eea54d86ccbdce0bf88929991d",
    },
    "@redact-secret/node-darwin-x64": {
        "version": "0.1.0-beta.13",
        "tarball": "sha512-Rx4yevnDtKmzOeLNBusHuWteUgjnv/et49VgSRTzstko1czjWbJzT0HS8oqXP3n02KWYYF2gJDD+Vy6fAfryfg==",
        "tree": "fff8a00c3f2e1e2d7100ab89cc8e8c62238854524ade7f7ba34cae33ffa8a0c6",
    },
    "@redact-secret/node-linux-arm64-gnu": {
        "version": "0.1.0-beta.13",
        "tarball": "sha512-7zD7nMn6ddbCGc4Vhung3twgWdLXg6FFiecoZbuNGTiXzgiOQoAlHwTDDWQniSm5XVCS2MkUWPZytJ7jbuH/oQ==",
        "tree": "6302fdd420acadcbe263e49a19d4baea6863ef4f4b23ec9af787899b25d16f91",
    },
    "@redact-secret/node-linux-arm64-musl": {
        "version": "0.1.0-beta.13",
        "tarball": "sha512-oDBtKusroKnDrj4ZZNBtX7l9dyupbKXaq0bL3c5kQANJuuhYxzaD5facGhLKU32uWQArrfsV2EfBgXuGR7pSpQ==",
        "tree": "bfaf3ffd08d4c6b2d6525b62ca3404967a6d777aaf5394fa6d03bfab808f8043",
    },
    "@redact-secret/node-linux-x64-gnu": {
        "version": "0.1.0-beta.13",
        "tarball": "sha512-V72Ay6vqmGGLZ5JS0UJ5wi0F4gBmKjh7wJLl8lskx0RCH3635I9UyJkmawsYrlcPTOpgKaVhFYZufsMNqa4cgA==",
        "tree": "7578a08c6143c78cedae88f12a6612728c94998f18e24333803cb1af3f3b4a5b",
    },
    "@redact-secret/node-linux-x64-musl": {
        "version": "0.1.0-beta.13",
        "tarball": "sha512-6+vldy/+uPPMNfDDo2sizg1JH2QhJ+5hj3Sc7pJo+ZhDDaUmoC+UsewemxLZUImuNI4oOy5+IFBsmQZK78ztAA==",
        "tree": "b124222853a22f093b6c2835919f4b434b525f4136c718cd36f0a45ebf6f2a27",
    },
    "@redact-secret/node-win32-arm64-msvc": {
        "version": "0.1.0-beta.13",
        "tarball": "sha512-yVeZEnP3eITXyagQ08at36ZESIGjGy/zHCZL2pkBiwC/e7GF4fyHAt/j2hfFT/dkFjXeQuZzQPhW+01kKeQLmQ==",
        "tree": "114ca1b4d0c6b1054b8c40f308a0ba1117c9aeac2f02daebf3746aa610849cab",
    },
    "@redact-secret/node-win32-x64-msvc": {
        "version": "0.1.0-beta.13",
        "tarball": "sha512-KpwzignFem2YD70jbvo4KvDG33E9lMPJLEKnHaWFMkwRM+DmXoQQVZEUUKa1SxCVCuWBmKslJ3wq7mnIm3qQsg==",
        "tree": "961dfd571a73c2a359f8f1ba90992e915ca280c66cf665ea93d0f51fbf47f8ba",
    },
}
