#!/usr/bin/env node
// One-time setup for the persistent example. Safe to run again.
//   1. create the unprivileged serving role
//   2. migrate the schema, as the owner
//   3. grant the serving role what the store needs, and nothing more
//   4. initialize the namespace
//   5. generate development-only keys
// Run: node examples/persistent/setup.mjs   (after `docker compose up -d`)
import { existsSync, writeFileSync } from "node:fs";

import pg from "pg";
import { createPostgresStore, grantStatements, migrate } from "@redact-secret/store-postgres";

import { ADMIN_URL, APP_URL, KEYS_FILE, NAMESPACE, RECOVERY_EPOCH, SCHEMA } from "./config.mjs";

const { username: role, password } = new URL(APP_URL);
if (!/^[a-z_][a-z0-9_]{0,62}$/.test(role)) throw new Error("the serving role name must be a plain lowercase identifier");

async function connectWithRetry(pool, attempts = 30) {
  for (let i = 1; ; i += 1) {
    try {
      await pool.query("SELECT 1");
      return;
    } catch (error) {
      if (i === attempts) throw new Error("PostgreSQL is not reachable. Did you run `docker compose up -d` in examples/persistent?");
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
  }
}

const owner = new pg.Pool({ connectionString: ADMIN_URL, max: 1 });
owner.on("error", () => {});
try {
  await connectWithRetry(owner);

  const existing = await owner.query("SELECT 1 FROM pg_roles WHERE rolname = $1", [role]);
  if (existing.rowCount === 0) {
    // CREATE ROLE takes no bind parameters; format() quotes the name and the password.
    const statement = await owner.query(
      "SELECT format('CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD %L', $1::text, $2::text) AS sql",
      [role, decodeURIComponent(password)],
    );
    await owner.query(statement.rows[0].sql);
  }
  console.log(`1. serving role ready: ${role}`);

  await migrate(owner, SCHEMA);
  console.log(`2. schema migrated: ${SCHEMA}`);

  for (const statement of grantStatements(SCHEMA, role)) await owner.query(statement);
  console.log("3. grants applied");
} finally {
  await owner.end();
}

// The namespace is initialized once, by a maintenance step like this one. A server never does it.
const pool = new pg.Pool({ connectionString: APP_URL, max: 1 });
pool.on("error", () => {});
try {
  const store = await createPostgresStore({ pool, schema: SCHEMA });
  const result = await store.initializeNamespace({ namespace: NAMESPACE, epoch: RECOVERY_EPOCH });
  if (result.outcome === "initialized") console.log(`4. namespace initialized: ${NAMESPACE} (epoch ${RECOVERY_EPOCH})`);
  else if (result.reason === "exists") console.log(`4. namespace already initialized: ${NAMESPACE}`);
  else throw new Error(`the namespace could not be initialized: ${result.reason}`);
  await store.close();
} finally {
  await pool.end();
}

if (existsSync(KEYS_FILE)) {
  console.log("5. development keys already present");
} else {
  const hex = () => Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString("hex");
  const keys = {
    warning: "Development only. Generated by examples/persistent/setup.mjs. A real server loads keys from a secret manager.",
    wrappingKey: hex(),
    digestKey: hex(),
  };
  writeFileSync(KEYS_FILE, `${JSON.stringify(keys, null, 2)}\n`, { mode: 0o600 });
  console.log("5. development keys generated (.dev-keys.json, git-ignored)");
}
console.log("\nready: node examples/persistent/demo.mjs");
