#!/usr/bin/env python3
"""Reproduce, write, and check the core integrity pin of the Python bridge.

The bridge (``packages/vault-py/src/redact_secret_vault/core_client.py``) refuses to scan unless the
``@redact-secret/core`` package it loads, the ``@redact-secret/wasm`` package it depends on, and the platform addon
package beside them hash to the digests pinned in ``packages/vault-py/src/redact_secret_vault/_core_pin.py``. This
script is the only thing that writes that file, and the check below runs in CI, so the pin cannot drift from the
version in ``package.json`` and the integrity values in ``package-lock.json`` without a failing build.

The digest ("rsv-tree-v1") of a package directory is SHA-256 over the text of one line per regular file, sorted by
the UTF-8 bytes of the POSIX relative path::

    <sha256 of the file's bytes, lowercase hex> <size in bytes> <relative path>\\n

A package directory that holds a symbolic link, a device, or anything but regular files and directories has no
digest. ``boundary/core_bridge.mjs`` implements the same function; ``tests/test_core_integrity.py`` checks that the
two agree on the installed core.

    python3 scripts/core-integrity.py check                 # offline: pin against package.json and package-lock.json
    python3 scripts/core-integrity.py check --fetch         # also download every tarball, verify the lock's sha512,
                                                            # and recompute every digest (needs the network; CI)
    python3 scripts/core-integrity.py check --installed node_modules   # also compare an installed tree
    python3 scripts/core-integrity.py write                 # rewrite the pin file (downloads, verifies, writes)

Standard library only. Prints names, versions, and digests; never a file's content.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import os
import re
import sys
import tarfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PIN_FILE = ROOT / "packages/vault-py/src/redact_secret_vault/_core_pin.py"
CORE_CLIENT = ROOT / "packages/vault-py/src/redact_secret_vault/core_client.py"
LOCKFILE = ROOT / "package-lock.json"
# The consumer-side install of release.yml's wheel smoke test: the same release, from its own lockfile.
SMOKE_LOCKFILE = ROOT / "scripts/python-wheel-smoke/package-lock.json"
ROOT_MANIFEST = ROOT / "package.json"

ALGORITHM = "rsv-tree-v1"
CORE = "@redact-secret/core"
WASM = "@redact-secret/wasm"
#: One package per platform the core publishes an addon for (its `optionalDependencies`).
ADDONS = (
    "@redact-secret/node-darwin-arm64",
    "@redact-secret/node-darwin-x64",
    "@redact-secret/node-linux-arm64-gnu",
    "@redact-secret/node-linux-arm64-musl",
    "@redact-secret/node-linux-x64-gnu",
    "@redact-secret/node-linux-x64-musl",
    "@redact-secret/node-win32-arm64-msvc",
    "@redact-secret/node-win32-x64-msvc",
)
PACKAGES = (CORE, WASM, *ADDONS)
MAX_TARBALL_BYTES = 64 * 1024 * 1024
HEX64 = re.compile(r"[0-9a-f]{64}")

HEADER = '''"""The pinned integrity of the Node.js core the bridge loads.

GENERATED by ``scripts/core-integrity.py write``; do not edit.

``tree`` is the "rsv-tree-v1" digest of the package's directory as npm installs it: SHA-256 over one line per regular
file, ``<sha256 of the content> <size> <relative path>`` sorted by the UTF-8 bytes of the path. ``tarball`` is the npm
``integrity`` value of the published tarball (``package-lock.json``), kept so that a reviewer can see the pin and the
lock agree. ``scripts/core-integrity.py check`` recomputes every ``tree`` from the published tarballs in CI.
"""

from __future__ import annotations

'''


def tree_digest_of_files(files: dict[str, bytes]) -> str:
    lines = []
    for rel in sorted(files, key=lambda r: r.encode("utf-8")):
        data = files[rel]
        lines.append(f"{hashlib.sha256(data).hexdigest()} {len(data)} {rel}\n")
    return hashlib.sha256("".join(lines).encode("utf-8")).hexdigest()


def tree_digest_of_dir(directory: Path) -> str:
    files: dict[str, bytes] = {}
    for current, dirs, names in os.walk(directory, followlinks=False):
        for entry in [*dirs, *names]:
            if (Path(current) / entry).is_symlink():
                raise SystemExit(f"{directory}: {entry} is a symbolic link; no digest")
        for name in names:
            path = Path(current) / name
            if not path.is_file():
                raise SystemExit(f"{directory}: {name} is not a regular file; no digest")
            files[path.relative_to(directory).as_posix()] = path.read_bytes()
    return tree_digest_of_files(files)


def tree_digest_of_tarball(data: bytes) -> str:
    files: dict[str, bytes] = {}
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        for member in tar:
            if member.isdir():
                continue
            if not member.isfile():
                raise SystemExit(f"tarball holds {member.name!r}, which is not a regular file; no digest")
            parts = member.name.split("/", 1)
            if parts[0] != "package" or len(parts) != 2 or ".." in parts[1].split("/"):
                raise SystemExit("tarball entry outside package/")
            extracted = tar.extractfile(member)
            assert extracted is not None
            files[parts[1]] = extracted.read()
    return tree_digest_of_files(files)


def sri_sha512(data: bytes) -> str:
    return "sha512-" + base64.b64encode(hashlib.sha512(data).digest()).decode()


def lock_entries() -> dict[str, dict[str, str]]:
    lock = json.loads(LOCKFILE.read_text())["packages"]
    entries = {}
    for name in PACKAGES:
        entry = lock.get(f"node_modules/{name}")
        if entry is None:
            raise SystemExit(f"package-lock.json has no entry for {name}")
        entries[name] = {"version": entry["version"], "resolved": entry["resolved"], "integrity": entry["integrity"]}
    return entries


def pinned_core_version() -> str:
    match = re.search(r'^PINNED_CORE_VERSION = "([^"]+)"$', CORE_CLIENT.read_text(), re.MULTILINE)
    if match is None:
        raise SystemExit("PINNED_CORE_VERSION not found in core_client.py")
    return match.group(1)


def download(url: str) -> bytes:
    if not url.startswith("https://registry.npmjs.org/"):
        raise SystemExit(f"refusing to download from {url.split('/')[2] if '//' in url else url}")
    with urllib.request.urlopen(url, timeout=120) as response:  # noqa: S310 - https, registry host checked above
        data = response.read(MAX_TARBALL_BYTES + 1)
    if len(data) > MAX_TARBALL_BYTES:
        raise SystemExit("tarball too large")
    return data


def load_pin() -> dict[str, dict[str, str]]:
    namespace: dict[str, object] = {}
    exec(compile(PIN_FILE.read_text(), str(PIN_FILE), "exec"), namespace)  # noqa: S102 - our own generated file
    pin = namespace["CORE_PACKAGES"]
    assert isinstance(pin, dict)
    if namespace.get("ALGORITHM") != ALGORITHM:
        raise SystemExit(f"{PIN_FILE.name}: algorithm is not {ALGORITHM}")
    return pin


def render(pin: dict[str, dict[str, str]]) -> str:
    out = [HEADER, f'ALGORITHM = "{ALGORITHM}"\n\n', "CORE_PACKAGES = {\n"]
    for name in PACKAGES:
        entry = pin[name]
        out.append(f'    "{name}": {{\n')
        for key in ("version", "tarball", "tree"):
            out.append(f'        "{key}": "{entry[key]}",\n')
        out.append("    },\n")
    out.append("}\n")
    return "".join(out)


def fetch_all(entries: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    result = {}
    for name, entry in entries.items():
        data = download(entry["resolved"])
        if sri_sha512(data) != entry["integrity"]:
            raise SystemExit(f"{name}@{entry['version']}: the downloaded tarball does not match package-lock.json")
        result[name] = {"version": entry["version"], "tarball": entry["integrity"], "tree": tree_digest_of_tarball(data)}
        print(f"  {name}@{entry['version']}: tarball verified, tree {result[name]['tree']}")
    return result


def check_offline(pin: dict[str, dict[str, str]], entries: dict[str, dict[str, str]]) -> list[str]:
    problems = []
    version = pinned_core_version()
    manifest = json.loads(ROOT_MANIFEST.read_text())
    root_pin = manifest.get("devDependencies", {}).get(CORE) or manifest.get("dependencies", {}).get(CORE)
    if root_pin != version:
        problems.append(f"package.json pins {CORE} {root_pin}; PINNED_CORE_VERSION is {version}")
    if set(pin) != set(PACKAGES):
        problems.append(f"the pin names {sorted(pin)}; expected {sorted(PACKAGES)}")
    for name in PACKAGES:
        entry, locked = pin.get(name), entries[name]
        if entry is None:
            continue
        if locked["version"] != version:
            problems.append(f"package-lock.json has {name}@{locked['version']}; PINNED_CORE_VERSION is {version}")
        if entry.get("version") != version:
            problems.append(f"the pin has {name}@{entry.get('version')}; PINNED_CORE_VERSION is {version}")
        if entry.get("tarball") != locked["integrity"]:
            problems.append(f"{name}: the pinned tarball integrity differs from package-lock.json")
        if not HEX64.fullmatch(entry.get("tree", "")):
            problems.append(f"{name}: the pinned tree digest is not 64 lowercase hex digits")
    return problems


def check_smoke_lock(pin: dict[str, dict[str, str]]) -> list[str]:
    """The wheel smoke test installs the core from its own lockfile; it must be the pinned release too."""
    if not SMOKE_LOCKFILE.is_file():
        return []
    packages = json.loads(SMOKE_LOCKFILE.read_text())["packages"]
    problems = []
    for name in PACKAGES:
        entry = packages.get(f"node_modules/{name}")
        if entry is None:
            problems.append(f"{SMOKE_LOCKFILE.relative_to(ROOT)} has no entry for {name}")
        elif entry.get("integrity") != pin[name]["tarball"] or entry.get("version") != pin[name]["version"]:
            problems.append(f"{SMOKE_LOCKFILE.relative_to(ROOT)}: {name} is not the pinned release")
    return problems


def check_installed(pin: dict[str, dict[str, str]], node_modules: Path) -> list[str]:
    problems = []
    found = 0
    for name in PACKAGES:
        directory = node_modules / name
        if not directory.is_dir():
            if name in (CORE, WASM):
                problems.append(f"{name} is not installed in {node_modules}")
            continue
        found += 1
        digest = tree_digest_of_dir(directory)
        if digest != pin[name]["tree"]:
            problems.append(f"{name}: the installed tree {digest} differs from the pin {pin[name]['tree']}")
        else:
            print(f"  {name}: installed tree matches the pin")
    if found < 3:
        problems.append("no platform addon package is installed to compare")
    return problems


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    check = sub.add_parser("check")
    check.add_argument("--fetch", action="store_true", help="download the tarballs and recompute every digest")
    check.add_argument("--installed", type=Path, help="a node_modules directory to compare with the pin")
    sub.add_parser("write")
    args = parser.parse_args(argv)

    entries = lock_entries()
    if args.command == "write":
        version = pinned_core_version()
        wrong = [f"{n}@{e['version']}" for n, e in entries.items() if e["version"] != version]
        if wrong:
            raise SystemExit(f"package-lock.json is not at {version}: {wrong}")
        PIN_FILE.write_text(render(fetch_all(entries)))
        print(f"wrote {PIN_FILE.relative_to(ROOT)}")
        return 0

    pin = load_pin()
    problems = check_offline(pin, entries)
    if not problems:
        problems += check_smoke_lock(pin)
    if args.fetch and not problems:
        for name, fresh in fetch_all(entries).items():
            if fresh["tree"] != pin[name]["tree"]:
                problems.append(f"{name}: the published tarball hashes to {fresh['tree']}; the pin says {pin[name]['tree']}")
    if args.installed is not None and not problems:
        problems += check_installed(pin, args.installed)
    for problem in problems:
        print(f"FAIL {problem}", file=sys.stderr)
    if problems:
        return 1
    print(
        f"core integrity pin: {len(pin)} packages at {pinned_core_version()} agree with package.json and package-lock.json"
        + (" and with the published tarballs" if args.fetch else "")
        + (" and with the installed tree" if args.installed else "")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
