#!/usr/bin/env python3
"""The one reproducible command for this repository's OpenGrep SAST baseline.

Copied from redact-secret/redact-secret (scripts/run-sast.py at 941053b); only
EXCLUSIONS differs. Issue numbers below refer to that repository.

    python3 scripts/run-sast.py

installs and verifies the pinned OpenGrep binary (see `install-opengrep.py`),
checks the vendored ruleset under `sast/rules` against its pinned digest,
scans this repository with it, normalizes the result into a structured
report, and enforces `sast/baseline.json`'s disposition of every finding and
every scan error. It exits non-zero -- and prints exactly what is
unclassified or blocking -- unless every finding is a recorded
`false_positive` or `hardening` item and every scan error is a recorded
`known_errors` entry. A `blocking` classification never passes: baselining
one silently would defeat the point of the classification.

This is deliberately a single gate over two different failure shapes:

- A *new finding* your ruleset has not seen before -- because you changed
  application code -- has no matching id in `sast/baseline.json` and fails
  the run until a human adds a disposition.
- A *scan error* -- a broken/unsupported rule, a rule or file timeout, a
  parse failure OpenGrep could not recover from -- is not a finding at all,
  but is exactly what issue #155's tamper tests require: it must not let the
  run silently report success. It is normalized into the same `errors` list
  and must be an acknowledged `known_errors` entry or the run fails.

Re-vendoring `sast/rules` at a new pinned revision, or widening the pinned
platform matrix, changes `compute_rules_digest`'s output; update
`sast/opengrep.lock.json`'s `rules.digest` deliberately when that happens --
this script fails closed if the on-disk ruleset and the pinned digest ever
disagree, so an unreviewed edit to a vendored rule file cannot pass silently
either.

`--sarif-out PATH` additionally renders the same normalized report as SARIF
2.1.0 (see `build_sarif`) for issue #156's CI upload to GitHub code
scanning. It is a projection of this same gate, never a second source of
truth: a finding already dispositioned as `false_positive`/`hardening` is
carried as a SARIF suppression rather than omitted, and a `blocking` or
unclassified finding is left unsuppressed -- exactly the findings that
already fail this run's exit code. GitHub ingestion does not apply those
suppressions to alert state by itself; the main-branch workflow synchronizes
them after processing. Whether upload or synchronization succeeds never
changes this script's own exit code.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_LOCK = DEFAULT_ROOT / "sast" / "opengrep.lock.json"
DEFAULT_RULES = DEFAULT_ROOT / "sast" / "rules"
DEFAULT_BASELINE = DEFAULT_ROOT / "sast" / "baseline.json"
DEFAULT_CACHE_DIR = DEFAULT_ROOT / ".cache" / "opengrep"
INSTALL_SCRIPT = Path(__file__).resolve().parent / "install-opengrep.py"

# Every excluded path, and why it is not application source this baseline
# should hold findings against. Kept as a single mapping so the exclusion
# list and its rationale cannot drift apart.
EXCLUSIONS: dict[str, str] = {
    ".git": "version-control internals, not source",
    "node_modules": "vendored third-party JavaScript dependencies",
    "dist": "TypeScript build output (generated by tsc)",
    ".qualification": "qualification reports and scratch consumers (generated)",
    ".claude": (
        "agent-tooling wiring generated and maintained by third-party CLIs "
        "(graft, rtk), not hand-authored application source"
    ),
    ".agents": "agent skill instructions (Markdown), not application source",
    "graft": "graft's local repository-graph cache; gitignored, regenerated by `graft build`",
    "conformance/v1": (
        "the adversarial corpus's synthetic secret-shaped fixtures; scanning deliberately "
        "secret-shaped text with a generic SAST tool is meaningless and risks a report "
        "copying secret-like values"
    ),
    "sast/rules": (
        "the vendored third-party OpenGrep rule definitions themselves; their embedded "
        "example patterns are not this project's source to remediate"
    ),
    "package-lock.json": "generated lockfile",
    "__pycache__": "generated Python bytecode cache",
}

VALID_CLASSIFICATIONS = {"blocking", "false_positive", "hardening"}


def _load_install_module():
    spec = importlib.util.spec_from_file_location("install_opengrep", INSTALL_SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def compute_rules_digest(rules_dir: Path) -> str:
    """sha256 over every vendored rule file's relative path paired with its
    own content hash, sorted by path -- independent of file system iteration
    order, and independent of `LICENSE.upstream`, which documents the
    vendored rules but is not itself a rule."""
    files = sorted(p for p in rules_dir.rglob("*") if p.is_file() and p.name != "LICENSE.upstream")
    digest = hashlib.sha256()
    for path in files:
        relative = path.relative_to(rules_dir).as_posix()
        content_hash = hashlib.sha256(path.read_bytes()).hexdigest()
        digest.update(f"{relative}\n{content_hash}\n".encode("utf-8"))
    return digest.hexdigest()


def finding_id(check_id: str, path: str, start_line: object, end_line: object) -> str:
    return hashlib.sha256(f"{check_id}|{path}|{start_line}|{end_line}".encode("utf-8")).hexdigest()[:16]


def error_id(error_type: str, path: str, line: object) -> str:
    return hashlib.sha256(f"{error_type}|{path}|{line}".encode("utf-8")).hexdigest()[:16]


def _error_type_and_location(error: dict) -> tuple[str, str, int]:
    """OpenGrep's `errors[].type` is sometimes a bare string and sometimes a
    `[name, locations]` pair (e.g. `PartialParsing`); normalize both to a
    type name plus a single representative file:line."""
    raw_type = error.get("type")
    if isinstance(raw_type, list):
        type_name = raw_type[0]
        locations = raw_type[1] if len(raw_type) > 1 and isinstance(raw_type[1], list) else []
    else:
        type_name = raw_type
        locations = []
    if locations:
        first = locations[0]
        path = first.get("path", "")
        line = first.get("start", {}).get("line", 0)
    else:
        path = error.get("path", "")
        line = 0
    return str(type_name), str(path), line


def normalize_report(*, raw: dict, tool_version: str, rules_digest: str, source_revision: str) -> dict:
    findings = []
    for result in raw.get("results", []):
        start = result.get("start", {})
        end = result.get("end", {})
        start_line = start.get("line")
        end_line = end.get("line")
        findings.append(
            {
                "id": finding_id(result["check_id"], result["path"], start_line, end_line),
                "rule_id": result["check_id"],
                "path": result["path"],
                "start_line": start_line,
                "end_line": end_line,
                "severity": result.get("extra", {}).get("severity", "UNKNOWN"),
                # The rule's own message, never the matched source snippet: this
                # report must never carry a copy of the scanned code itself, so
                # a secret-shaped match (however unlikely under these rules)
                # cannot leak plaintext into the baseline or CI logs.
                "message": result.get("extra", {}).get("message", ""),
            }
        )
    errors = []
    for error in raw.get("errors", []):
        type_name, path, line = _error_type_and_location(error)
        message = (error.get("message") or "").splitlines()[0] if error.get("message") else ""
        errors.append(
            {
                "id": error_id(type_name, path, line),
                "type": type_name,
                "path": path,
                "line": line,
                "message": message,
            }
        )
    return {
        "tool": "opengrep",
        "tool_version": tool_version,
        "rules_digest": rules_digest,
        "source_revision": source_revision,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "findings": sorted(findings, key=lambda f: (f["path"], f["start_line"] or 0, f["rule_id"])),
        "errors": sorted(errors, key=lambda e: (e["path"], e["line"], e["type"])),
    }


SARIF_SCHEMA = "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json"
SARIF_VERSION = "2.1.0"

# OpenGrep's own severities, mapped onto SARIF's fixed `level` vocabulary.
# Anything unrecognized (including "UNKNOWN") is reported, never dropped.
SARIF_LEVEL_BY_SEVERITY = {
    "ERROR": "error",
    "WARNING": "warning",
    "INFO": "note",
}


def build_sarif(*, report: dict, baseline: dict) -> dict:
    """Render `report` as SARIF 2.1.0 for GitHub code scanning.

    Issue #156 requires the SARIF upload to never become the sole
    enforcement signal, so this is a projection of the same normalized
    report `check_baseline` already gates on -- never an independent source
    of truth. A finding already dispositioned as `false_positive` or
    `hardening` in `sast/baseline.json` is carried as a SARIF `suppression`
    (kind `external`, with the recorded rationale). GitHub ingestion preserves
    that data but does not apply it to alert state by itself; the main-branch
    workflow's pinned dismissal action performs that synchronization. A
    `blocking` or not-yet-classified finding is left unsuppressed, since it is
    exactly what already fails the run. Only the rule's own `message` is ever
    included, matching `normalize_report` -- never a matched snippet.
    """
    findings_baseline = baseline.get("findings", {})
    rule_ids = sorted({finding["rule_id"] for finding in report["findings"]})
    rules = [{"id": rule_id, "name": rule_id} for rule_id in rule_ids]

    results = []
    for finding in report["findings"]:
        entry = findings_baseline.get(finding["id"], {})
        classification = entry.get("classification")
        result: dict = {
            "ruleId": finding["rule_id"],
            "level": SARIF_LEVEL_BY_SEVERITY.get(finding["severity"], "warning"),
            "message": {"text": finding["message"] or finding["rule_id"]},
            "partialFingerprints": {"opengrepFindingId/v1": finding["id"]},
            "locations": [
                {
                    "physicalLocation": {
                        "artifactLocation": {"uri": finding["path"]},
                        "region": {
                            "startLine": finding["start_line"] or 1,
                            "endLine": finding["end_line"] or finding["start_line"] or 1,
                        },
                    }
                }
            ],
        }
        if classification in ("false_positive", "hardening"):
            result["suppressions"] = [
                {
                    "kind": "external",
                    "justification": entry.get("rationale", "reviewed and dispositioned in sast/baseline.json"),
                }
            ]
        results.append(result)

    return {
        "version": SARIF_VERSION,
        "$schema": SARIF_SCHEMA,
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "OpenGrep",
                        "version": report.get("tool_version", "unknown"),
                        "informationUri": "https://github.com/opengrep/opengrep",
                        "rules": rules,
                    }
                },
                "results": results,
            }
        ],
    }


def load_baseline(path: Path) -> dict:
    if not path.is_file():
        return {"findings": {}, "known_errors": {}}
    return json.loads(path.read_text(encoding="utf-8"))


def check_baseline(report: dict, baseline: dict) -> list[str]:
    """Enforce issue #155's disposition rule. Returns a human-readable
    problem per unclassified finding, invalid classification, blocking
    finding, or unacknowledged scan error -- empty when the run may pass."""
    problems: list[str] = []
    findings_baseline = baseline.get("findings", {})
    for finding in report["findings"]:
        entry = findings_baseline.get(finding["id"])
        location = f"{finding['rule_id']} at {finding['path']}:{finding['start_line']}"
        if entry is None:
            problems.append(f"UNCLASSIFIED finding {finding['id']} ({location}): add a disposition to the baseline")
            continue
        classification = entry.get("classification")
        if classification not in VALID_CLASSIFICATIONS:
            problems.append(f"finding {finding['id']} ({location}): invalid classification {classification!r}")
        elif classification == "blocking":
            rationale = entry.get("rationale", "no rationale recorded")
            problems.append(f"BLOCKING finding {finding['id']} ({location}): {rationale}")
    errors_baseline = baseline.get("known_errors", {})
    for error in report["errors"]:
        if error["id"] not in errors_baseline:
            location = f"{error['type']} at {error['path']}:{error['line']}"
            problems.append(f"UNACKNOWLEDGED scan error {error['id']} ({location}): add it to known_errors")
    return problems


def run_scan(*, opengrep_binary: Path, rules_dir: Path, repo_root: Path, timeout: int, targets: list[str]) -> dict:
    exclude_args = []
    for pattern in EXCLUSIONS:
        exclude_args += ["--exclude", pattern]
    result = subprocess.run(
        [
            str(opengrep_binary),
            "scan",
            "--config",
            str(rules_dir),
            "--json",
            "--timeout",
            str(timeout),
            *exclude_args,
            *(targets or ["."]),
        ],
        cwd=repo_root,
        capture_output=True,
        text=True,
        timeout=max(timeout, 1) * 200 + 300,
    )
    if not result.stdout.strip():
        raise RuntimeError(f"opengrep produced no output (exit {result.returncode}): {result.stderr[-4000:]}")
    return json.loads(result.stdout)


def git_revision(repo_root: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo_root), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
    )
    return result.stdout.strip()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    parser.add_argument("--repo-root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--lock", type=Path, default=DEFAULT_LOCK)
    parser.add_argument("--rules", type=Path, default=DEFAULT_RULES)
    parser.add_argument("--baseline", type=Path, default=DEFAULT_BASELINE)
    parser.add_argument("--cache-dir", type=Path, default=DEFAULT_CACHE_DIR)
    parser.add_argument("--out", type=Path, default=None, help="write the normalized report as JSON")
    parser.add_argument(
        "--sarif-out", type=Path, default=None, help="write the report as SARIF 2.1.0 for code scanning upload"
    )
    parser.add_argument("--timeout", type=int, default=30, help="opengrep --timeout, seconds per rule per file")
    parser.add_argument("--binary", type=Path, default=None, help="skip install/verify, use this opengrep binary")
    parser.add_argument("target", nargs="*", help="paths to scan (default: the whole repo root)")
    args = parser.parse_args(argv)

    install_module = _load_install_module()
    lock = install_module.load_lock(args.lock)

    pinned_digest = lock["rules"]["digest"]
    actual_digest = compute_rules_digest(args.rules)
    if actual_digest != pinned_digest:
        print(
            "FAIL-CLOSED: sast/rules does not match sast/opengrep.lock.json's pinned rules digest "
            f"(pinned {pinned_digest}, actual {actual_digest}); the vendored ruleset was edited "
            "without a deliberate re-pin",
            file=sys.stderr,
        )
        return 1

    if args.binary is not None:
        binary_path = args.binary
    else:
        try:
            platform_key = install_module.detect_platform_key()
            binary_path = install_module.install(
                lock=lock,
                platform_key=platform_key,
                cache_dir=args.cache_dir,
                downloader=install_module.urllib_downloader,
                cosign_runner=install_module.real_cosign_runner,
            )
        except install_module.VerificationFailed as error:
            print(f"FAIL-CLOSED: {error}", file=sys.stderr)
            return 1

    version_result = subprocess.run([str(binary_path), "--version"], capture_output=True, text=True, timeout=30)
    tool_version = version_result.stdout.strip()
    if tool_version != lock["opengrep_version"]:
        print(
            f"FAIL-CLOSED: opengrep --version reported {tool_version!r}, "
            f"expected the pinned {lock['opengrep_version']!r}",
            file=sys.stderr,
        )
        return 1

    try:
        raw = run_scan(
            opengrep_binary=binary_path,
            rules_dir=args.rules,
            repo_root=args.repo_root,
            timeout=args.timeout,
            targets=args.target,
        )
    except (RuntimeError, subprocess.TimeoutExpired, json.JSONDecodeError) as error:
        print(f"FAIL-CLOSED: opengrep scan did not produce a usable report: {error}", file=sys.stderr)
        return 1

    report = normalize_report(
        raw=raw,
        tool_version=tool_version,
        rules_digest=actual_digest,
        source_revision=git_revision(args.repo_root),
    )

    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    baseline = load_baseline(args.baseline)

    if args.sarif_out is not None:
        sarif = build_sarif(report=report, baseline=baseline)
        args.sarif_out.parent.mkdir(parents=True, exist_ok=True)
        args.sarif_out.write_text(json.dumps(sarif, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    problems = check_baseline(report, baseline)
    for problem in problems:
        print(f"ERROR {problem}", file=sys.stderr)
    print(
        f"OpenGrep SAST: {len(report['findings'])} finding(s), {len(report['errors'])} scan error(s), "
        f"{len(problems)} unresolved"
    )
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
